// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Author      string   `json:"author"`
	PublishedAt *string  `json:"publishedAt,omitempty"`
	Inputs      []*Input `json:"inputs"`
}

type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Input struct {
	ID      string    `json:"id"`
	BookID  string    `json:"bookId"`
	Content string    `json:"content"`
	Outputs []*Output `json:"outputs"`
}

type Mutation struct {
}

type Output struct {
	ID      string `json:"id"`
	InputID string `json:"inputId"`
	Action  string `json:"action"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type User struct {
	ID       string  `json:"id"`
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Books    []*Book `json:"books"`
}
