// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Input struct {
	ID              string    `json:"id"`
	ResourceID      string    `json:"resourceId"`
	InputName       string    `json:"inputName"`
	InputDetail     string    `json:"inputDetail"`
	InputCategoryID string    `json:"inputCategoryId"`
	Outputs         []*Output `json:"outputs"`
}

type Mutation struct {
}

type Output struct {
	ID               string `json:"id"`
	InputID          string `json:"inputId"`
	OutputName       string `json:"outputName"`
	OutputDetail     string `json:"outputDetail"`
	OutputCategoryID string `json:"outputCategoryId"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Resource struct {
	ID                 string   `json:"id"`
	UserID             string   `json:"userId"`
	ResourceName       string   `json:"resourceName"`
	ResourceDetail     string   `json:"resourceDetail"`
	ResourceCategoryID string   `json:"resourceCategoryId"`
	Inputs             []*Input `json:"inputs"`
}

type User struct {
	ID        string      `json:"id"`
	UserName  string      `json:"userName"`
	Age       int         `json:"age"`
	Resources []*Resource `json:"resources"`
}
