// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Input struct {
	ID         string    `json:"id"`
	ResourceID string    `json:"resourceId"`
	CategoryID string    `json:"categoryId"`
	Name       string    `json:"name"`
	Detail     string    `json:"detail"`
	Outputs    []*Output `json:"outputs"`
}

type Mutation struct {
}

type Output struct {
	ID         string `json:"id"`
	InputID    string `json:"inputId"`
	CategoryID string `json:"categoryId"`
	Name       string `json:"name"`
	Detail     string `json:"detail"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Resource struct {
	ID         string   `json:"id"`
	UserID     string   `json:"userId"`
	Name       string   `json:"name"`
	CategoryID string   `json:"categoryId"`
	Inputs     []*Input `json:"inputs"`
}

type User struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Age       int         `json:"age"`
	Resources []*Resource `json:"resources"`
}
