// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Input struct {
	ID              string    `json:"id"`
	ResourceID      string    `json:"resourceId"`
	InputName       string    `json:"inputName"`
	InputDetail     *string   `json:"inputDetail,omitempty"`
	InputCategoryID int       `json:"inputCategoryId"`
	CreatedAt       DateTime  `json:"createdAt"`
	UpdatedAt       DateTime  `json:"updatedAt"`
	Outputs         []*Output `json:"outputs"`
}

type Mutation struct {
}

type Output struct {
	ID               string   `json:"id"`
	InputID          string   `json:"inputId"`
	OutputName       string   `json:"outputName"`
	OutputDetail     *string  `json:"outputDetail,omitempty"`
	OutputCategoryID int      `json:"outputCategoryId"`
	CreatedAt        DateTime `json:"createdAt"`
	UpdatedAt        DateTime `json:"updatedAt"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Resource struct {
	ID                 string   `json:"id"`
	UserID             string   `json:"userId"`
	ResourceName       string   `json:"resourceName"`
	ResourceDetail     *string  `json:"resourceDetail,omitempty"`
	ResourceCategoryID int      `json:"resourceCategoryId"`
	CreatedAt          DateTime `json:"createdAt"`
	UpdatedAt          DateTime `json:"updatedAt"`
	Inputs             []*Input `json:"inputs"`
}

type User struct {
	ID        string      `json:"id"`
	Nickname  string      `json:"nickname"`
	Birthday  *string     `json:"birthday,omitempty"`
	Age       *int        `json:"age,omitempty"`
	CreatedAt DateTime    `json:"createdAt"`
	UpdatedAt DateTime    `json:"updatedAt"`
	Resources []*Resource `json:"resources"`
}
