package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"

	"github.com/take0fit/knowledge-out/interface/gql/generated"
	"github.com/take0fit/knowledge-out/interface/gql/model"
	"github.com/take0fit/knowledge-out/internal/application/dto"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, nickname string, birthday *model.DateTime) (*model.User, error) {
	inputUser := dto.NewInputCreateUser(nickname, birthday.Time)
	user, err := r.userUsecase.CreateUser(ctx, inputUser)
	if err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	gqlUser := &model.User{
		ID:       user.Id,
		Nickname: user.Nickname,
		Age:      user.Age,
	}

	return gqlUser, err
}

// CreateResource is the resolver for the createResource field.
func (r *mutationResolver) CreateResource(ctx context.Context, userID string, resourceName string, resourceDetail *string, resourceCategoryID int) (*model.Resource, error) {
	inputResource := dto.NewInputCreateResource(
		userID,
		resourceName,
		resourceDetail,
		resourceCategoryID,
	)
	resource, err := r.resourceUsecase.CreateResource(ctx, inputResource)
	if err != nil {
		return nil, fmt.Errorf("failed to create resource: %w", err)
	}

	gqlResource := &model.Resource{
		ID:           resource.Id,
		ResourceName: resource.Name,
	}

	return gqlResource, err
}

// CreateInput is the resolver for the createInput field.
func (r *mutationResolver) CreateInput(ctx context.Context, userID string, resourceID string, inputName string, inputDetail *string, inputCategoryID int) (*model.Input, error) {
	panic(fmt.Errorf("not implemented: CreateInput - createInput"))
}

// CreateOutput is the resolver for the createOutput field.
func (r *mutationResolver) CreateOutput(ctx context.Context, userID string, inputIds []string, outputName string, outputDetail *string, outputCategoryID int) (*model.Output, error) {
	panic(fmt.Errorf("not implemented: CreateOutput - createOutput"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.userUsecase.GetUserList()
	if err != nil {
		return nil, err
	}

	var gqlUsers []*model.User
	for _, user := range users {
		gqlUsers = append(gqlUsers, &model.User{
			ID:       user.Id,
			Nickname: user.Nickname,
			Age:      user.Age,
		})
	}

	return gqlUsers, err
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	user, err := r.userUsecase.GetUserDetails(id)
	if err != nil {
		return nil, err
	}

	gqlUser := &model.User{
		ID:        user.Id,
		Nickname:  user.Nickname,
		Resources: nil,
	}

	return gqlUser, err
}

// Resources is the resolver for the resources field.
func (r *queryResolver) Resources(ctx context.Context) ([]*model.Resource, error) {
	panic(fmt.Errorf("not implemented: Resources - resources"))
}

// Resource is the resolver for the resource field.
func (r *queryResolver) Resource(ctx context.Context, id string) (*model.Resource, error) {
	panic(fmt.Errorf("not implemented: Resource - resource"))
}

// Inputs is the resolver for the inputs field.
func (r *queryResolver) Inputs(ctx context.Context) ([]*model.Input, error) {
	panic(fmt.Errorf("not implemented: Inputs - inputs"))
}

// Input is the resolver for the input field.
func (r *queryResolver) Input(ctx context.Context, id string) (*model.Input, error) {
	panic(fmt.Errorf("not implemented: Input - input"))
}

// Outputs is the resolver for the outputs field.
func (r *queryResolver) Outputs(ctx context.Context) ([]*model.Output, error) {
	panic(fmt.Errorf("not implemented: Outputs - outputs"))
}

// Output is the resolver for the output field.
func (r *queryResolver) Output(ctx context.Context, id string) (*model.Output, error) {
	panic(fmt.Errorf("not implemented: Output - output"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
